name: symphonyinc
services:
  web:
    api: 4
    #image: alpine:3.18.3
    volumes:
      - ./:/app
    image:
      imagefile: |
        FROM debian:latest
        # 1. Copy essential files
        COPY scripts /etc/lando
        COPY scripts/env-detect.sh  /etc/lando/lash.d/002-env-detect.sh
        COPY scripts/log.sh /etc/lando/lash.d/001-log.sh
        # 2. Install lash
        COPY lash.sh /bin/lash
        RUN chmod +x /bin/lash
        # 3. Setup landorc.sh for BASH
        ENV BASH_ENV=/etc/lando/landorc.sh
        # 4. Run Boot
        RUN /etc/lando/boot.sh
        # 5. Switch to lash
        SHELL ["/bin/lash", "-c"]
        RUN lando_blue "Switched to lash and loaded Lando logger." 
        # 6. Usermapping
        RUN /etc/lando/usermap.sh www-data 501
        CMD tail -f /dev/null